### ISSUE TITLE
sentences_example.py Exception: API 不可用!

### ISSUE THREAD

**Issue by al123xiaaaa** [sunhailin-Leo/deepL-translator-api#1]
python .\sentences_example.py

{'result': 'It was a beautiful day and I went hiking with Xiao Ming.We met Little Red in the mountains and happily wrote code together.'}
Traceback (most recent call last):
  File ".\sentences_example.py", line 46, in <module>
    sentences_translate_example_en_to_zh()
  File ".\sentences_example.py", line 27, in sentences_translate_example_en_to_zh
    translate_mode=TranslateModeType.SENTENCES,
  File "C:\Users\xiagw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydeeplator\deepL.py", line 117, in translate
    return self._translate_sentences()
  File "C:\Users\xiagw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydeeplator\deepL.py", line 161, in _translate_sentences
    return self._prepare_call_translate_api(job_dict_list=job_dict_list, lang=lang)
  File "C:\Users\xiagw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydeeplator\deepL.py", line 178, in _prepare_call_translate_api
    translate_result = self._core_request(request_data=translate_data)
  File "C:\Users\xiagw\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pydeeplator\deepL.py", line 199, in _core_request
    raise Exception("API 不可用!")
Exception: API 不可用!

**Comment by Master-Antonio** [comment]
Same.
Did you fix in some way?

**Comment by sunhailin-Leo** [comment]
@al123xiaaaa 
* Fixed it

**Comment by lazidoca** [comment]
It looks like the issue still happens
