### ISSUE TITLE
sentence_example.py Exception

### ISSUE THREAD

**Issue by Master-Antonio** [sunhailin-Leo/deepL-translator-api#2]
Your example generate a error.
```
Traceback (most recent call last):
  File "test.py", line 46, in <module>
    sentences_translate_example_en_to_zh()
  File "test.py", line 24, in sentences_translate_example_en_to_zh
    result = DeepLTranslator(
  File "pydeeplator\deepL.py", line 117, in translate
    return self._translate_sentences()
  File "pydeeplator\deepL.py", line 161, in _translate_sentences
    return self._prepare_call_translate_api(job_dict_list=job_dict_list, lang=lang)
  File "pydeeplator\deepL.py", line 178, in _prepare_call_translate_api
    translate_result = self._core_request(request_data=translate_data)
  File "pydeeplator\deepL.py", line 199, in _core_request
    raise Exception("API 不可用!")
Exception: API 不可用!

Process finished with exit code 1
```

**Comment by sunhailin-Leo** [comment]
@Master-Antonio 
* Fixed it
